### ISSUE TITLE
RemoteFork

### ISSUE THREAD

**Issue by ghost** [bobi/ForkPlayer_webOS#1]
Приветствую. 
Можно ли убрать зависимость RemoteFork для ресурсов там где он требуется? 
Ведь при установке как нативное приложение для запуска нам не требуется подменять DNS, мы можем использовать любые. К примеру на андройд версии, такой зависимости нет.

**Comment by bobi** [comment]
Я не понял вопроса. О каких ресурсах идёт речь?

**Comment by ghost** [comment]
Речь идет о сайтах, которые не работают без RemoteFork. (tree.tv, zona и т.д) 
А не работают они потому, что им требуются DNS не ForkPlayer, поэтому и ставится RemoteFork. 
Если же установить ForkPlayer через пакет разработчика, то для запуска нам не нужно подменять DNS от ForkPlayer. Ввиду этого эти сайты должны работать при таком способе установки без RemoteFork, но приложение требует его установки. Версия плеера для андройд (aForkPlayer) воспроизводит видео с этих сайтов без установки RemoteFork. Можно ли сделать воспроизведение с этих сайтов без RemoteFork при нативной установке приложения на наш тв?  Надеюсь понятно объяснил XD

**Comment by bobi** [comment]
Теперь понятно,  я не видел исходников для для андроид Forkplayer, но думаю там просто встроен RemoteFork. На телевизоре если это и возможно то будет очень сложно сделать. Проще всего установить RemoteFork на NAS или роутер https://github.com/bobi/ForkPlayer (у меня так работает) Можно даже попробовать установить на телевизор.


Версия Forkplayer для web os была сделана чтобы была возможность автозапуска на web os.
